### ISSUE TITLE
KeyError: 'env'

### ISSUE THREAD

**Issue by eeeebbbbrrrr** [SethMichaelLarson/trytravis#12]
Trying to run trytravis on macOS 10.13 Beta 8 after following the installation/configuration instructions (I'm using an existing GitHub repo w/ Travis integration):

```
$ trytravis
Adding a temporary remote to `ssh://git@github.com/zombodb/zombodb`...
Adding all local changes...
Committing local changes...
Pushing to `trytravis` remote...
Waiting for a Travis build to appear for `d9c3b4e52e8370698868ba5c2d45108d18e0c9c7` after `2017-08-21T17:42:52-06:00`...
Travis build id: `268070345`
Travis build URL: `https://travis-ci.org/zombodb/zombodb/builds/268070345`
Travis build id: `266996379`
Travis build URL: `https://travis-ci.org/zombodb/zombodb/builds/266996379`
Traceback (most recent call last):
  File "/usr/local/bin/trytravis", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/trytravis.py", line 373, in main
    _main(argv)
  File "/Library/Python/2.7/site-packages/trytravis.py", line 364, in _main
    _watch_travis_build(build_id)
  File "/Library/Python/2.7/site-packages/trytravis.py", line 250, in _watch_travis_build
    env = job['config']['env']
KeyError: 'env'
```

I'm not sure if this `KeyError: 'env'` thing is coming from trytravis or the remote travis build?

Maybe other relevant information:

```shell
$ uname -a
Darwin emacpro28.lan 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 22:01:05 PDT 2017; root:xnu-4570.1.46~3/RELEASE_X86_64 x86_64
```

```shell
$ pip --version
pip 9.0.1 from /Library/Python/2.7/site-packages (python 2.7)
```

```shell
$ python --version
Python 2.7.10
```

If I can provide other details please let me know.

**Comment by SethMichaelLarson** [comment]
`env` is supposed to be provided after fetching the build information from the API endpoint `/builds/[build_id]` so I'll do some querying and figure out why that's not getting included in the payload for that endpoint.

**Comment by eeeebbbbrrrr** [comment]
Ahh!  Sounds easy enough.  Leave it to me to have done things differently!

**Comment by SethMichaelLarson** [comment]
Fixed this in the latest, pushed `1.0.2` to PyPI. You can run `python -m pip install -U trytravis` to upgrade. Thanks! :tada:

**Comment by eeeebbbbrrrr** [comment]
Done.  The env KeyError is gone, so that's good!

Maybe I'm misunderstanding something about trytravis, but my average build time on travis-ci is almost 10 minutes.  Yes, when I run trytravis, it returns to the shell in about 6 seconds:

```
$ time trytravis 
Adding a temporary remote to `ssh://git@github.com/zombodb/zombodb`...
Adding all local changes...
Committing local changes...
Pushing to `trytravis` remote...
Waiting for a Travis build to appear for `d9c3b4e52e8370698868ba5c2d45108d18e0c9c7` after `2017-08-21T17:42:52-06:00`...
Travis build id: `268070345`
Travis build URL: `https://travis-ci.org/zombodb/zombodb/builds/268070345`
Travis build id: `266996379`
Travis build URL: `https://travis-ci.org/zombodb/zombodb/builds/266996379`
#1 P linux s java 

real	0m5.926s
user	0m0.608s
sys	0m0.641s
```

And I don't see any activity on my project's travis-ci build history (should I?).  

Am I a doofus somehow?  My most amazing .travis.yml is [located here](https://github.com/zombodb/zombodb/blob/master/.travis.yml).

**Comment by SethMichaelLarson** [comment]
Oh you want to create a different repository not the repo you're targeting the changes to. I need to setup a bigger warning for that...

**Comment by SethMichaelLarson** [comment]
Like in my case I have `SethMichaelLarson/trytravis-target` and that'll work for all my projects.

**Comment by SethMichaelLarson** [comment]
So what I'm guessing is you didn't have any local changes and then ran trytravis, it tried to add changes but there weren't any and then it globbed onto the build that was for that commit that had already run through CI?

**Comment by eeeebbbbrrrr** [comment]
>Oh you want to create a different repository not the repo you're targeting the changes to. I need to setup a bigger warning for that...

Oh!  I see.  I misunderstood the instructions as being "how to setup trytravis for new project", not "you need a 'dummy' target repo".

> So what I'm guessing is you didn't have any local changes and then ran trytravis, it tried to add changes but there weren't any and then it globbed onto the build that was for that commit that had already run through CI?

Yep.  Exactly what happened.

Lemme do it the right way and I'll report back.

ps, does trytravis stream the log output?  That would be amazing!

**Comment by SethMichaelLarson** [comment]
Sorry about that! I just had an idea about a feature to make this mistake extremely hard to make. I definitely need to add that before someone mucks up their repository.

It doesn't stream the log output sadly! It would be tough to implement the feature for people with multiple jobs.

**Comment by eeeebbbbrrrr** [comment]
running it now with my new `trytravis-target` repo.

I'm wondering if it's possible to push with a depth of 1, so that it's only pushing the contents of HEAD + local changes?

Maybe the initial full push only needs to happen once?

**Comment by SethMichaelLarson** [comment]
That's true, for larger repositories that could be an issue.

**Comment by eeeebbbbrrrr** [comment]
(also, it's building now.  This is great! <3)

**Comment by SethMichaelLarson** [comment]
I'm glad it's working! And I totally agree, it's definitely not a restriction for the API :) Maybe that could be a future improvement (or tbh, a whole different project for a command-line based Travis API)

**Comment by eeeebbbbrrrr** [comment]
There's this:  https://github.com/travis-ci/travis.rb

Could ya integrate with it easily to tail the build output?

**Comment by SethMichaelLarson** [comment]
I wouldn't need to use that, I could probably grab the output and stream it from Amazon S3

**Comment by eeeebbbbrrrr** [comment]
You have already made the world a better place.  Much appreciated!

**Comment by SethMichaelLarson** [comment]
Thank you so much! I was just in the middle of writing up an issue to explore the streaming and being a more interactive CLI
