### ISSUE TITLE
Force users to use a repository with `trytravis` in the name.

### ISSUE THREAD

**Issue by SethMichaelLarson** [SethMichaelLarson/trytravis#13]
This should reduce the amount of mistakes and hopefully force users to make new repositories.

**Comment by eeeebbbbrrrr** [comment]
Ya know, could this instead be intuited based on the repo name of the current working directory instead?  Maybe just require that the repo name be $CURRENT_REPO-trytravis?

This would also eliminate the need to run `trytravis --repo`, would let users use this across multiple projects, and you could output a nice error like "Please create a repo named $CURRENT_REPO-trytravis".

Thoughts?

**Comment by SethMichaelLarson** [comment]
Can't do that because once you setup your `trytravis` target you can use it for any project. :)

**Comment by eeeebbbbrrrr** [comment]
oh, well, that's good -- was another thing I misunderstood.

**Comment by SethMichaelLarson** [comment]
That's fine, I actually toyed with this idea earlier on! :D

**Comment by SethMichaelLarson** [comment]
Resolved this issue with 1.0.3
