### ISSUE TITLE
"Wait for results" mode

### ISSUE THREAD

**Issue by haikuginger** [SethMichaelLarson/trytravis#15]
It'd be nice to have a command I can run post-push that will

1. Find the build for the commit I just pushed
2. Show the build status
3. When the build completes, print the bell character (`\a`) to notify me.

It'd be nice to have the bell ring either when all sub-builds complete successfully or when any single build fails (to get my attention so I can check the logs to find the failure point).

Really, I guess the bell would be pretty useful regardless of mode, so maybe this should be two separate issues (1: find the build for the commit I just pushed; 2: add bells to the build that's currently being observed).

**Comment by SethMichaelLarson** [comment]
This is a great idea, definitely on my list of things to do! Thanks! :tada:
