### ISSUE TITLE
Output Travis URL and stop

### ISSUE THREAD

**Issue by miguelbalparda** [SethMichaelLarson/trytravis#17]
Is there any way to stop the wait until the builds are done? I'd like to output the matrix and the url but not wait until all the builds are done. Amazing work btw!

**Comment by SethMichaelLarson** [comment]
Thanks! That's a good suggestion :) I'll add it to my list. Maybe something like `--no-wait`?

**Comment by miguelbalparda** [comment]
Yes definitely. I'll try to submit a PR, but don't expect much since I don't know python lol.

**Comment by SethMichaelLarson** [comment]
Sounds good to me! And don't worry about it I'll help you if you need it :) Good luck!
