### ISSUE TITLE
Times out while build already runs

### ISSUE THREAD

**Issue by einball** [SethMichaelLarson/trytravis#18]
I'm using trytravis on a test repository of mine which only contains some test files to be able to test trytravis properly. My procedure (after installing a completely fresh Ubuntu Server 17.04, git, python and the rest):

```
root@vm~$: pip install trytravis
[...] Success
einball@vm~$: git clone ssh://git@github.com/einball/trytravis
[...] Success
einball@vm~$: trytravis -r ssh://git@github.com/einball/trytravis
[...] Success
einball@vm~$: cd trytravis
einball@vm~$: echo ' ' >> README.md && trytravis
Adding a temporary remote to `ssh://git@github.com/einball/trytravis`...
Adding all local changes...
Committing local changes...
Pushing to `trytravis` remote...
Reverting to old state...
Waiting for a Travis build to appear for `1546a2a2ee5e6ff340e848a2315ecf66373c17b7` after `2017-08-30T16:34:49+02:00`...
ERROR: Timed out while waiting for a Travis build to start. Is Travis configured for `ssh://git@github.com/einball/trytravis`?
Adding a temporary remote to `ssh://git@github.com/einball/trytravis`...
Adding all local changes...
Committing local changes...
Pushing to `trytravis` remote...
Reverting to old state...
Waiting for a Travis build to appear for `1546a2a2ee5e6ff340e848a2315ecf66373c17b7` after `2017-08-30T16:34:49+02:00`...
ERROR: Timed out while waiting for a Travis build to start. Is Travis configured for `ssh://git@github.com/einball/trytravis`?
einball@vm~$:
```
The build that should have been triggered would be this [Travis Build]( https://travis-ci.org/einball/trytravis/builds/270020427 ). It got triggered, but trytravis just times out instead of grabbing the right build from TravisCI! There's no error message to be shown.

I'd love to give more input, but there is no more (yet). The problem seems to be in line 212 to 219 but I haven't had the time yet to look further into it:
https://github.com/SethMichaelLarson/trytravis/blob/3620a708020b3ced6b9c69caee9b4942b69815b8/trytravis.py#L212-L219

**Comment by SethMichaelLarson** [comment]
I wonder if this has to do with timezone issues... I'll look into this. Does it occur every time?

**Comment by SethMichaelLarson** [comment]
Jere's just an info dump of stuff I see from the API.

```json
{"id":270020427,
"repository_id":15009079,
"number":"4",
"state":"finished",
"result":0,
"started_at":"2017-08-30T14:35:59Z",
"finished_at":"2017-08-30T14:36:36Z",
"duration":37,
"commit":"1546a2a2ee5e6ff340e848a2315ecf66373c17b7",
"branch":"master",
"message":"trytravis-2017-08-30T16:34:49.706095",
"event_type":"push"}
```

`"committed_at":"2017-08-30T14:34:49Z"`
`2017-08-30T16:34:49+02:00`

This could potentially be the issue?

**Comment by SethMichaelLarson** [comment]
I'm almost positive this is what's breaking for you, cuz you have a positive UTC offset.
Will submit a fix and a new release for you to try. Thank you for submitting this!

**Comment by SethMichaelLarson** [comment]
When you get a chance can you try the latest `master`? Works for me but I live in a negative UTC offset.

**Comment by einball** [comment]
Commit 2f8e47a fixes the erratic behavior. It was, indeed, a timezone issue :+1: 

```
einball@vm:~/trytravis$ trytravis 
Adding a temporary remote to `ssh://git@github.com/einball/trytravis`...
Adding all local changes...
Committing local changes...
Pushing to `trytravis` remote...
Reverting to old state...
Waiting for a Travis build to appear for `9ce551dd77c4b4e3b33547300a08af30695ba29e` after `2017-08-30 22:25:37`...
Travis build id: `270116649`
Travis build URL: `https://travis-ci.org/einball/trytravis/builds/270116649`
#1 * linux s python TEST_DIR=${TRAVIS_BUILD_DIR}/test
#1 * linux s python TEST_DIR=${TRAVIS_BUILD_DIR}/test
#1 P linux s python TEST_DIR=${TRAVIS_BUILD_DIR}/test
```

**Comment by SethMichaelLarson** [comment]
Great! I'll release this change then you can upgrade to the latest with `pip`. :) :tada:
