### ISSUE TITLE
Timeout waiting for travis-vi

### ISSUE THREAD

**Issue by reenberg** [SethMichaelLarson/trytravis#23]
I'm getting the following error

```
ERROR: Timed out while waiting for a Travis build to start. Is Travis configured for `ssh://git@github.com/reenberg/trytravis.git`?
```

As far as I can tell, then travis is waiting "to boot", and then `trytravis` errors with the timeout, and then travis-ci actually begins running.  

However I can't figure out if this is the issue, or if `trytravis` actually can't find the job because of something else.  It newer returns a "build id" or a "build URL"

Besides that the repo is getting built by travis-ci, when you look at the travis-ci.org webpage

**Comment by reenberg** [comment]
Ah, some debugging resolved the issue, as always.  It turns out that when specifying the `--repo` url, then you have to remove the "*.git*" suffix, that you get when copying the clone url from e.g. github.

It would be nice if the tool could just take the url in the form that you get it from github, without you having to prefix with "*ssh://*" and change the ":" to a "/" before the username.

**Comment by SethMichaelLarson** [comment]
Glad you were able to resolve this issue. :)

**Comment by reenberg** [comment]
Perhaps a note in the README, about not having .git in the url, if you don't think it should be auto handled.  Since it almost works if you do.
