### ISSUE TITLE
Times out waiting for build

### ISSUE THREAD

**Issue by RazerM** [SethMichaelLarson/trytravis#24]
Perhaps similar to #18. I'm on v1.0.4 which I think should contain that bug fix.

I see the following:
```
Waiting for a Travis build to appear for `7ce8f12df455cbd7807dc680be2a2434451232db` after `2017-10-21 00:32:52`...
ERROR: Timed out while waiting for a Travis build to start. Is Travis configured for <repo>
```

> 2017-10-21 00:32:52

My local time is 2017-10-20T22:32:52+02:00, but the shown time is 4 hours ahead of UTC.

**Comment by SethMichaelLarson** [comment]
If you could figure out why trytravis isn't getting your local time correctly that would solve the issue.

**Comment by bergpb** [comment]
I'm found this error after install latest version:

`ERROR: Timed out while waiting for a Travis build to start. Is Travis configured for ssh://git@github.com/user/repo`

Time showed in datetime is diferent from my local machine time:
```Waiting for a Travis build to appear for `...` after `2020-01-05 08:24:45`...```
Local time: 21:09
